// reports/templates/typst-template.typ — PNT Moni Typst PDF shell
// (ADR 0017 Phase D). Replaces Quarto's default `typst-template.typ`
// partial via `format: typst > template-partials` in each monthly_*.qmd.
//
// Palette + brand font names come from the GENERATED module
// pntmoni-brand.typ (vendored from pntmoni-docs/60-brand/tokens.json —
// NEVER hand-edit it; regenerate with `node 60-brand/generate-tokens.mjs`).
// This file adds the system-font fallbacks, the provenance cover
// (`pm-cover`, adapted from the 2026-07 design handoff:
// pntmoni-docs/60-brand/design-handoff-2026-07/typst/report-template.typ)
// and the body shell (`article`) that the typst-show partial calls.
//
// FONTS: system-installed only (ADR 0017 — no webfont download or
// embedding). The brand families (IBM Plex Sans JP / Noto Sans JP /
// IBM Plex Mono) are listed first; on machines without them Typst
// prints "unknown font family" WARNINGS (non-fatal) and falls through
// to the appended system faces (Hiragino Sans for CJK, Menlo for mono).

#import "pntmoni-brand.typ": *

// Font stacks = brand stack (generated) + system fallbacks.
#let pm-sans-stack = pm-sans + ("Hiragino Sans",)
#let pm-mono-stack = pm-mono + ("Menlo", "Hiragino Sans")

// Mono numerals with tabular figures (local variant of the generated
// pm-num, on the fallback-extended mono stack).
#let pm-mononum(body) = text(font: pm-mono-stack, features: ("tnum",))[#body]

// Outline-hexagon wordmark glyph. Drawn (not typeset): U+2B21 "⬡" has
// no glyph in Hiragino Sans / Menlo, so the character would render as
// tofu on a system-font-only machine.
#let pm-hexmark(size: 12pt, stroke: 1.4pt + pm-gold) = box(
  baseline: 12%,
  polygon(
    stroke: stroke,
    ..range(6).map(i => {
      let a = 90deg + i * 60deg
      (size / 2 * (1 + calc.cos(a)), size / 2 * (1 - calc.sin(a)))
    }),
  ),
)

// ---- Provenance cover (証跡) ------------------------------------------
// Dark ink banner + gold rule + provenance table. Field VALUES are
// injected at render time by each template's `typst-cover` cell (a raw
// ```{=typst}``` block built from the driver-injected params — see
// PNTMONI_REPORT_PARAMS in src/pntmoni_pipeline/reports/driver.py).
// The cell can only UPDATE the state below (Quarto wraps cell output in
// a #block container, where `set page` / `pagebreak` are forbidden), so
// the actual cover + TOC are rendered by `article` at document level
// via pm-cover-data.final(). Title/subtitle come from the document
// metadata (typst-show), so the cover follows the language profile.
#let pm-cover-data = state("pm-cover-data", none)
#let pm-cover(
  title: none,
  subtitle: none,
  eyebrow: "MONTHLY REPORT",
  month: "—",
  published: "—",
  methodology: "—",
  config-hash: "—",
  dataset: "—",
  labels: (
    month: "対象月",
    published: "公開日",
    methodology: "方法論バージョン",
    config-hash: "config hash",
    dataset: "dataset",
  ),
  note: "メーカー・行政機関から独立した第三者評価。スポンサー・広告なし。評価手法は公開後不変。",
  colophon: "© 2026 pntmoni · generated by Quarto + Typst",
) = {
  set page(margin: 0pt, numbering: none, header: none, footer: none)
  // dark ink banner + gold rule
  block(fill: pm-ink, width: 100%, inset: (x: 40pt, top: 48pt, bottom: 36pt))[
    #text(fill: white, font: pm-sans-stack, weight: 700, size: 20pt)[#pm-hexmark() pntmoni]
    #v(20pt)
    #line(length: 44pt, stroke: 3pt + pm-gold)
    #v(18pt)
    #text(fill: rgb("#9AA1B4"), font: pm-mono-stack, size: 9pt, tracking: 0.08em)[#eyebrow]
    #v(6pt)
    #text(fill: white, font: pm-sans-stack, weight: 700, size: 24pt)[#title]
    #v(6pt)
    #text(fill: pm-on-dark, font: pm-sans-stack, size: 12pt)[#subtitle]
  ]
  // provenance table (証跡): muted label left, mono value right
  pad(x: 40pt, top: 28pt)[
    #set text(font: pm-sans-stack, size: 10pt)
    #let row(k, v) = (
      text(fill: pm-muted)[#k],
      align(right, pm-mononum(text(fill: pm-ink, weight: 600)[#v])),
    )
    #table(
      columns: (1fr, auto), stroke: none,
      inset: (y: 8pt),
      ..row(labels.month, month),
      table.hline(stroke: 0.5pt + pm-border),
      ..row(labels.published, published),
      table.hline(stroke: 0.5pt + pm-border),
      ..row(labels.methodology, methodology),
      table.hline(stroke: 0.5pt + pm-border),
      ..row(labels.config-hash, config-hash),
      table.hline(stroke: 0.5pt + pm-border),
      ..row(labels.dataset, dataset),
    )
  ]
  v(1fr)
  // independence note + colophon pinned to the page foot
  pad(x: 40pt, bottom: 40pt)[
    #text(fill: pm-faint, font: pm-sans-stack, size: 9pt)[#note]
    #v(6pt)
    #text(fill: rgb("#B8BDC9"), font: pm-mono-stack, size: 8pt)[#colophon]
  ]
  pagebreak()
}

// ---- Document shell ------------------------------------------------
// Page geometry/numbering come from Quarto's page partial (driven by
// the `papersize` / `margin` / `page-numbering` format options), so no
// `set page` here. No title block either — the cover replaces it; the
// title still lands in the PDF metadata via `set document`.
#let article(
  title: none,
  subtitle: none,
  authors: none,
  date: none,
  keywords: (),
  lang: "en",
  region: none,
  fontsize: 10.5pt,
  sectionnumbering: none,
  toc: false,
  toc_title: none,
  toc_depth: 3,
  toc_indent: 1.5em,
  doc,
) = {
  set document(title: title) if title != none
  set text(font: pm-sans-stack, size: fontsize, fill: pm-text, lang: lang)
  set text(region: region) if region != none
  set par(justify: true, leading: 0.72em)
  set heading(numbering: sectionnumbering)

  // Headings: sans 700 ink; H1 carries the section rule (handoff).
  show heading.where(level: 1): it => block(above: 1.6em, below: 0.8em)[
    #set text(font: pm-sans-stack, weight: 700, size: 15pt, fill: pm-ink)
    #it
    #v(-0.3em)
    #line(length: 100%, stroke: 1.5pt + pm-ink)
  ]
  show heading.where(level: 2): set text(font: pm-sans-stack, weight: 700, size: 12pt, fill: pm-ink)
  show heading.where(level: 3): set text(font: pm-sans-stack, weight: 700, size: 11pt, fill: pm-ink)

  show link: set text(fill: pm-blue)
  show raw: set text(font: pm-mono-stack, size: 0.9em)

  // Tables: Tufte-ish rules (ink under the header, hairlines between
  // rows) + tabular numerals throughout.
  set table(
    inset: 6pt,
    stroke: (x, y) => if y == 0 { (bottom: 1pt + pm-ink) } else { (bottom: 0.5pt + pm-border) },
  )
  show table: set text(features: ("tnum",))
  show figure.caption: set text(size: 9pt, fill: pm-muted)
  // Captioned tables (Quarto wraps them in #figure with kind
  // "quarto-float-tbl") MUST be breakable: a Typst figure defaults to
  // an unbreakable block, and an unbreakable figure taller than one
  // page does not spill to the next page — Typst squashes the trailing
  // rows on top of each other at the page bottom (observed on the
  // 2026-06 editions' NAQU/NANU/NAGU events and GPS-constellation
  // tables; reproduced in isolation with the bundled Typst 0.14.2).
  // Scoped to table floats so image figures keep their keep-together
  // placement; `table.header` rows repeat automatically on each page.
  show figure.where(kind: "quarto-float-tbl"): set block(breakable: true)
  // ...and rows stay atomic when a table breaks (no mid-row cell splits
  // at the page boundary): wrapping each cell in an unbreakable block
  // makes a row that no longer fits move to the next page as a whole
  // (longtable-like). Verified not to perturb auto column sizing or
  // per-cell alignment (right / horizon) on the bundled Typst 0.14.2.
  //
  // Underscore-joined tokens (event-type values like
  // `scheduled_maintenance`, sourced verbatim from the outage
  // parquet) have no break opportunity, so under Typst's "auto"
  // column-width negotiation a wide neighbor column (e.g. a long
  // `severity` value like `informational`) can squeeze the token's
  // column below the token's natural width — the unbreakable text
  // then overprints the next cell rather than wrapping (observed on
  // the 2026-06 CLAS-rapid PDFs' NAQU/NANU/NAGU events table;
  // reproduced in isolation with the bundled Typst 0.14.2). Insert a
  // zero-width space after each literal "_" so the line breaker gets
  // an optional break point there; this only adds an opportunity, it
  // never forces a break, so cells that already fit their column are
  // unaffected. Scoped inside the table.cell show rule so no other
  // text (headings, prose, captions) is touched.
  show table.cell: it => block(breakable: false, inset: 0pt)[
    #show "_": "_" + sym.zws
    #it
  ]

  // Provenance cover + TOC, driven by the typst-cover cell's state
  // update (none when a template renders without the cover cell). The
  // dict's optional `toc-title` key requests a TOC after the cover.
  context {
    let c = pm-cover-data.final()
    if c != none {
      let toc-t = c.at("toc-title", default: none)
      let args = (:)
      for (k, v) in c {
        if k != "toc-title" { args.insert(k, v) }
      }
      pm-cover(title: title, subtitle: subtitle, ..args)
      if toc-t != none {
        block(above: 0em, below: 2em)[
          #outline(title: toc-t, depth: toc_depth, indent: toc_indent)
        ]
        pagebreak(weak: true)
      }
    }
  }

  // Plain Quarto toc (only if a template opts back in with `toc: true`;
  // the monthly templates use the cover-cell TOC above instead).
  if toc {
    block(above: 0em, below: 2em)[
      #outline(title: toc_title, depth: toc_depth, indent: toc_indent)
    ]
  }

  doc
}
